---
- name: Install docker
  become: yes
  remote_user: ubuntu
  hosts: all

  tasks:    
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default Docker image
      docker_image:
        name: "ubuntu"
        source: pull

    - name: Access to docker socks
      shell: "chmod 666 /var/run/docker.sock"
      become_user: root
      become: yes      
      args:
        executable: /bin/bash      

    - name: Install docker-compose
      pip: 
        name: docker-compose
        executable: pip3
      become: yes
    
    - name: copy Docker Compose files
      template:
          src: docker-compose.yaml
          dest: /home/ubuntu/docker-compose.yaml    

    - name: deploy Docker Compose stack
      docker_compose:
        project_src: ./
        files:
          - docker-compose.yaml       