---
- name: Install docker
  become: yes
  remote_user: ubuntu
  hosts: all

  tasks:    
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Pull default Docker image
      docker_image:
        name: "ubuntu"
        source: pull

    - name: Access to docker socks
      shell: "chmod 666 /var/run/docker.sock"
      become_user: root
      become: yes      
      args:
        executable: /bin/bash      

    - name: Install docker-compose
      remote_user: ubuntu
      get_url: 
        url : https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    - name: copy Docker Compose files
      copy:
        src: ./{{ item }}
        dest: ./{{ item }}
      loop:
        - docker-compose.yml      

    - name: deploy Docker Compose stack
      docker_compose:
        project_src: ./
        files:
          - docker-compose.yml       